import { useState } from "react";
import axios from "axios";
import "./Dashboard.css";

const API_URL = "http://localhost:5001";

function Dashboard() {
  const [header, setHeader] = useState("");
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // =====================================================
  // HEADER ANALYSIS
  // =====================================================

  const analyzeHeader = async () => {
    if (!header.trim()) {
      setError("Please paste an email header.");
      return;
    }

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const response = await axios.post(
        `${API_URL}/analyze`,
        {
          header: header,
        }
      );

      console.log("HEADER ANALYSIS RESPONSE:", response.data);

      const forensicResult =
        response.data?.report ||
        response.data?.data ||
        response.data;

      setResult(forensicResult);
    } catch (err) {
      console.error("HEADER ANALYSIS ERROR:", err);

      setError(
        err.response?.data?.details ||
        err.response?.data?.error ||
        err.response?.data?.message ||
        err.message ||
        "Unable to analyze the email header."
      );
    } finally {
      setLoading(false);
    }
  };

  // =====================================================
  // EML FILE ANALYSIS
  // =====================================================

  const analyzeFile = async () => {
    if (!file) {
      setError("Please select an .eml file.");
      return;
    }

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const formData = new FormData();

      // Phase 3 expects field name: email
      formData.append("email", file);

      const response = await axios.post(
        `${API_URL}/analyze-file`,
        formData
      );

      console.log("EML ANALYSIS RESPONSE:", response.data);

      const forensicResult =
        response.data?.report ||
        response.data?.data ||
        response.data;

      setResult(forensicResult);
    } catch (err) {
      console.error("EML ANALYSIS ERROR:", err);

      setError(
        err.response?.data?.details ||
        err.response?.data?.error ||
        err.response?.data?.message ||
        err.message ||
        "Unable to analyze the EML file."
      );
    } finally {
      setLoading(false);
    }
  };

  // =====================================================
  // CLEAR
  // =====================================================

  const clearAnalysis = () => {
    setHeader("");
    setFile(null);
    setResult(null);
    setError("");

    const fileInput = document.getElementById("emlFile");

    if (fileInput) {
      fileInput.value = "";
    }
  };

  // =====================================================
  // STATUS CLASS
  // =====================================================

  const getStatusClass = (value) => {
    if (!value) {
      return "status-unknown";
    }

    const text = String(value).toLowerCase();

    if (text.includes("softfail")) {
      return "status-warning";
    }

    if (text === "pass") {
      return "status-pass";
    }

    if (text === "fail") {
      return "status-fail";
    }

    if (text.includes("neutral")) {
      return "status-neutral";
    }

    return "status-unknown";
  };

  // =====================================================
  // RISK CLASS
  // =====================================================

  const getRiskClass = (score) => {
    const value = Number(score);

    if (value >= 70) {
      return "risk-high";
    }

    if (value >= 40) {
      return "risk-medium";
    }

    return "risk-low";
  };

  // =====================================================
  // REAL PHASE 3 V2 RESULT MAPPING
  // =====================================================

  // Risk
  const riskScore =
    result?.riskAssessment?.riskScore ??
    null;

  const classification =
    result?.riskAssessment?.classification ??
    null;

  const riskDescription =
    result?.riskAssessment?.description ??
    "Risk assessment generated by the forensic engine.";

  // Sender
  const sender =
    result?.senderAnalysis?.from ??
    null;

  const domain =
    result?.senderAnalysis?.fromDomain ??
    null;

  // IP
  const ipv4 =
    result?.ipAnalysis?.ipv4?.[0] ??
    null;

  const ipv6 =
    result?.ipAnalysis?.ipv6?.[0] ??
    null;

  // Routing
  const routingHops =
    result?.routingAnalysis?.hopCount ??
    null;

  // Authentication
  const spf =
    result?.verificationSummary?.spf?.result ??
    result?.authenticationAnalysis?.spf?.result ??
    null;

  const dkim =
    result?.verificationSummary?.dkim?.result ??
    result?.authenticationAnalysis?.dkim?.result ??
    null;

  const dmarc =
    result?.verificationSummary?.dmarc?.result ??
    result?.authenticationAnalysis?.dmarc?.result ??
    null;

  // Findings
  const findings =
    result?.suspiciousFindings ??
    [];

  // Conclusion
  const forensicConclusion =
    result?.forensicConclusion ??
    null;

  // =====================================================
  // DISPLAY VALUE
  // =====================================================

  const displayValue = (value) => {
    if (
      value === null ||
      value === undefined ||
      value === ""
    ) {
      return "Not available";
    }

    return String(value);
  };

  // =====================================================
  // PAGE
  // =====================================================

  return (
    <div className="forensic-dashboard">

      {/* =================================================
          HEADER
      ================================================= */}

      <header className="forensic-header">

        <div className="brand-section">

          <div className="brand-symbol">
            ✉
          </div>

          <div>
            <h1>
              Email Header Investigation Analyzer
            </h1>

            <p>
              Digital Forensic Email Analysis Platform
            </p>
          </div>

        </div>

        <div className="final-label">
          FINAL FORENSIC ANALYSIS
        </div>

      </header>


      {/* =================================================
          MAIN
      ================================================= */}

      <main className="dashboard-container">

        {/* =================================================
            INPUT SECTION
        ================================================= */}

        <section className="investigation-panel">

          <div className="section-heading">

            <div>
              <h2>
                Email Investigation
              </h2>

              <p>
                Analyze an email header or upload an EML
                file for forensic examination.
              </p>
            </div>

            {result && (
              <button
                className="clear-button"
                onClick={clearAnalysis}
              >
                Clear Analysis
              </button>
            )}

          </div>


          <div className="analysis-input-grid">

            {/* HEADER */}

            <div className="input-section">

              <h3>
                Paste Email Header
              </h3>

              <p className="input-description">
                Paste the complete raw email header below.
              </p>

              <textarea
                value={header}
                onChange={(e) =>
                  setHeader(e.target.value)
                }
                placeholder={
                  "From: sender@example.com\n" +
                  "To: recipient@example.com\n" +
                  "Received: ...\n" +
                  "Authentication-Results: ..."
                }
              />

              <button
                className="analyze-button"
                onClick={analyzeHeader}
                disabled={loading}
              >
                {loading
                  ? "Analyzing..."
                  : "Analyze Header"}
              </button>

            </div>


            {/* EML */}

            <div className="eml-section">

              <div className="upload-symbol">
                📎
              </div>

              <h3>
                Upload EML File
              </h3>

              <p>
                Upload the original .eml file for
                complete forensic analysis.
              </p>

              <label
                htmlFor="emlFile"
                className="file-label"
              >
                Choose EML File
              </label>

              <input
                id="emlFile"
                type="file"
                accept=".eml,message/rfc822"
                onChange={(e) => {
                  setFile(
                    e.target.files?.[0] || null
                  );

                  setError("");
                }}
              />

              {file && (
                <div className="selected-file">
                  <span>📄</span>
                  <span>{file.name}</span>
                </div>
              )}

              <button
                className="analyze-button"
                onClick={analyzeFile}
                disabled={loading}
              >
                {loading
                  ? "Analyzing..."
                  : "Analyze EML File"}
              </button>

            </div>

          </div>


          {/* ERROR */}

          {error && (
            <div className="error-message">
              <strong>
                Analysis Error:
              </strong>

              <span>
                {error}
              </span>
            </div>
          )}

        </section>


        {/* =================================================
            RESULTS
        ================================================= */}

        {result && (
          <section className="forensic-results">

            {/* RESULTS HEADER */}

            <div className="results-header">

              <div>
                <h2>
                  Forensic Analysis Results
                </h2>

                <p>
                  Results generated by the Phase 3
                  forensic authentication engine.
                </p>
              </div>

              <div className="analysis-complete">
                ✓ ANALYSIS COMPLETE
              </div>

            </div>


            {/* =================================================
                RISK
            ================================================= */}

            <div className="risk-dashboard">

              <div className="risk-main">

                <span>
                  OVERALL RISK SCORE
                </span>

                <div
                  className={`risk-value ${
                    riskScore !== null
                      ? getRiskClass(riskScore)
                      : "risk-medium"
                  }`}
                >
                  {displayValue(riskScore)}
                </div>

                <small>
                  Risk scale: 0–100
                </small>

              </div>


              <div className="risk-classification">

                <span>
                  THREAT CLASSIFICATION
                </span>

                <strong
                  className={
                    riskScore !== null
                      ? getRiskClass(riskScore)
                      : "risk-medium"
                  }
                >
                  {displayValue(classification)}
                </strong>

                <p>
                  {riskDescription}
                </p>

              </div>

            </div>


            {/* =================================================
                AUTHENTICATION
            ================================================= */}

            <div className="dashboard-section">

              <div className="section-title">
                Authentication Verification
              </div>

              <div className="authentication-grid">

                {/* SPF */}

                <div className="authentication-card">

                  <div className="auth-name">
                    SPF
                  </div>

                  <div
                    className={`auth-status ${getStatusClass(
                      spf
                    )}`}
                  >
                    {displayValue(spf)}
                  </div>

                  <p>
                    Sender Policy Framework
                  </p>

                </div>


                {/* DKIM */}

                <div className="authentication-card">

                  <div className="auth-name">
                    DKIM
                  </div>

                  <div
                    className={`auth-status ${getStatusClass(
                      dkim
                    )}`}
                  >
                    {displayValue(dkim)}
                  </div>

                  <p>
                    DomainKeys Identified Mail
                  </p>

                </div>


                {/* DMARC */}

                <div className="authentication-card">

                  <div className="auth-name">
                    DMARC
                  </div>

                  <div
                    className={`auth-status ${getStatusClass(
                      dmarc
                    )}`}
                  >
                    {displayValue(dmarc)}
                  </div>

                  <p>
                    Domain-based Message Authentication
                  </p>

                </div>

              </div>

            </div>


            {/* =================================================
                SENDER
            ================================================= */}

            <div className="dashboard-section">

              <div className="section-title">
                Sender & Routing Information
              </div>

              <div className="information-grid">

                <div className="information-item">
                  <span>Sender</span>
                  <strong>
                    {displayValue(sender)}
                  </strong>
                </div>

                <div className="information-item">
                  <span>Domain</span>
                  <strong>
                    {displayValue(domain)}
                  </strong>
                </div>

                <div className="information-item">
                  <span>IPv4 Address</span>
                  <strong>
                    {displayValue(ipv4)}
                  </strong>
                </div>

                <div className="information-item">
                  <span>IPv6 Address</span>
                  <strong>
                    {displayValue(ipv6)}
                  </strong>
                </div>

                <div className="information-item">
                  <span>Routing Hops</span>
                  <strong>
                    {displayValue(routingHops)}
                  </strong>
                </div>

              </div>

            </div>


            {/* =================================================
                FINDINGS
            ================================================= */}

            <div className="dashboard-section">

              <div className="section-title">
                Suspicious Findings
              </div>

              <div className="findings-dashboard">

                {findings.length > 0 ? (

                  findings.map(
                    (finding, index) => {

                      const code =
                        finding?.code ||
                        "Finding";

                      const severity =
                        finding?.severity ||
                        "unknown";

                      const message =
                        finding?.message ||
                        String(finding);

                      return (
                        <div
                          className="finding-row"
                          key={index}
                        >

                          <span className="finding-icon">
                            ⚠
                          </span>

                          <div className="finding-content">

                            <strong>
                              {code}
                            </strong>

                            <span
                              className={`severity-${severity.toLowerCase()}`}
                            >
                              {severity.toUpperCase()}
                            </span>

                            <p>
                              {message}
                            </p>

                          </div>

                        </div>
                      );
                    }
                  )

                ) : (

                  <div className="no-findings">
                    ✓ No suspicious findings were
                    reported by the forensic engine.
                  </div>

                )}

              </div>

            </div>


            {/* =================================================
                FORENSIC REPORT
            ================================================= */}

            <div className="dashboard-section">

              <div className="section-title">
                Forensic Report
              </div>

              <div className="forensic-report">

                <div className="report-heading">
                  Investigation Summary
                </div>

                <p>
                  The analyzed email received an
                  overall risk score of{" "}
                  <strong>
                    {displayValue(riskScore)}
                  </strong>{" "}
                  out of 100.
                </p>

                <p>
                  The forensic engine classified
                  this message as{" "}
                  <strong>
                    {displayValue(classification)}
                  </strong>.
                </p>


                <div className="report-grid">

                  <div>
                    <span>SPF</span>

                    <strong
                      className={getStatusClass(spf)}
                    >
                      {displayValue(spf)}
                    </strong>
                  </div>

                  <div>
                    <span>DKIM</span>

                    <strong
                      className={getStatusClass(dkim)}
                    >
                      {displayValue(dkim)}
                    </strong>
                  </div>

                  <div>
                    <span>DMARC</span>

                    <strong
                      className={getStatusClass(dmarc)}
                    >
                      {displayValue(dmarc)}
                    </strong>
                  </div>

                  <div>
                    <span>Sender</span>

                    <strong>
                      {displayValue(sender)}
                    </strong>
                  </div>

                  <div>
                    <span>Domain</span>

                    <strong>
                      {displayValue(domain)}
                    </strong>
                  </div>

                  <div>
                    <span>Source IP</span>

                    <strong>
                      {displayValue(ipv4)}
                    </strong>
                  </div>

                  <div>
                    <span>Routing Hops</span>

                    <strong>
                      {displayValue(routingHops)}
                    </strong>
                  </div>

                </div>


                {/* FORENSIC CONCLUSION */}

                {forensicConclusion && (
                  <div className="forensic-conclusion">

                    <strong>
                      Forensic Conclusion
                    </strong>

                    <p>
                      {forensicConclusion}
                    </p>

                  </div>
                )}


                <div className="report-note">

                  This report summarizes the actual
                  results returned by the Phase 3 V2
                  forensic analysis engine.

                </div>

              </div>

            </div>

          </section>
        )}

      </main>


      {/* FOOTER */}

      <footer className="dashboard-footer">

        Email Header Investigation Analyzer

        <span>•</span>

        Phase 5 Final Dashboard

        <span>•</span>

        Digital Forensics

      </footer>

    </div>
  );
}

export default Dashboard;